spring:
  application:
    name: Evenement-microservice # Nom de l'application pour identification dans Eureka

  cloud:
    config:
      uri: http://localhost:8888 # Adresse de votre Config Server
      import: "optional:config-server:" # Utilisation correcte de configserver avec optional pour éviter l'erreur
    import-check:
      enabled: false # Désactiver la vérification de l'importation de configuration

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761 # Adresse de votre Eureka Server

  # Configuration de la base de données
  datasource:
    url: jdbc:mysql://localhost:3306/B2
    
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuration JPAac
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  spring:
   sleuth:
    enabled: false  # Désactive Spring Cloud Sleuth, ce qui désactive aussi Zipkin


server:
  port: 8085

